export const products = [
    {
      id: 1,
      name: "Alexa Smart Speaker",
      available: 14,
      price: 21.99,
      Quantyti: 0,
      TotalAmount: 0,
    },
    {
      id: 2,
      name: "Apple Watch",
      available: 5,
      price: 429,
      Quantyti: 0,
      TotalAmount: 0,
    },
    {
      id: 3,
      name: "Kindle Paperwhite",
      available: 7,
      price: 69.99,
      Quantyti: 0,
      TotalAmount: 0,
    },
    {
      id: 4,
      name: "Sony 40-inch Flat screen",
      available: 3,
      price: 349.99,
      Quantyti: 0,
      TotalAmount: 0,
    },
    {
      id: 5,
      name: "Apple iPad pro 12.9-inch",
      available: 3,
      price: 799.99,
      Quantyti: 0,
      TotalAmount: 0,
    },
    {
      id: 6,
      name: "Samsung Galaxy Tablet",
      available: 8,
      price: 129.99,
      Quantyti: 0,
      TotalAmount: 0,
    },
    {
      id: 7,
      name: "Acer Aspire Laptop",
      available: 2,
      price: 369.99,
      Quantyti: 0,
      TotalAmount: 0,
    },
  ];
  